# Generated by Django 5.0.1 on 2024-01-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
    ]
